# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_notebook_path": "00_core.ipynb",
         "find_default_export_for_notebook": "00_core.ipynb",
         "get_module_name": "00_core.ipynb",
         "get_package_name": "00_core.ipynb",
         "reload_package_modules": "00_core.ipynb",
         "export_and_reload_all": "00_core.ipynb",
         "run_process": "00_core.ipynb",
         "get_run_python_args": "00_core.ipynb",
         "build_and_push_docker_image": "00_core.ipynb",
         "format_job_dir": "00_core.ipynb",
         "print_tensorboard_command": "00_core.ipynb",
         "AcceleratorType": "ai_platform_constants.ipynb",
         "ScaleTier": "ai_platform_constants.ipynb",
         "MachineType": "ai_platform_constants.ipynb",
         "DistributionStrategyType": "ai_platform_constants.ipynb",
         "run_docker_image": "kubernetes_runner.ipynb",
         "run_package": "ai_platform_runner.ipynb",
         "get_distribution_strategy_instance": "entry_point.ipynb",
         "parse_unknown_args": "entry_point.ipynb",
         "setup_keras_tuner_config": "entry_point.ipynb",
         "main": "entry_point.ipynb",
         "some_function_to_run_on_cloud": "sample_code_test.ipynb",
         "run_python": "local_runner.ipynb",
         "run_docker": "local_runner.ipynb",
         "run_on_ai_platform": "local_runner.ipynb"}

modules = ["core.py",
           "ai_platform_constants.py",
           "ai_platform_runner.py",
           "entry_point.py",
           "index.py",
           "kubernetes_runner.py",
           "local_runner.py",
           "sample_code_test.py"]

doc_url = "https://users.github.io/gcp_runner/"

git_url = "https://github.com/users/gcp_runner/tree/master/"

def custom_doc_links(name): return None
