# AUTOGENERATED! DO NOT EDIT! File to edit: entry_point.ipynb (unless otherwise specified).

__all__ = ['main']

# Cell
import os
import argparse
import time
import importlib
import inspect

def main():
    print('in gcp_runner entry point')
    args_parser = argparse.ArgumentParser()
    args_parser.add_argument(
        '--module-name',
        help='module name of an app to run',
        required=True)
    args_parser.add_argument(
        '--function-name',
        help='function name to run',
        required=True)

    args, unknown_args = args_parser.parse_known_args()
    print('running entrypoint function: %s.%s' % (args.module_name, args.function_name))
    module = importlib.import_module(args.module_name)
    func = getattr(module, args.function_name)
    if unknown_args is not None and len(unknown_args) > 0:
        print('additional args: %s' % str(unknown_args))
        args_spec = inspect.getargspec(func)
        if args_spec is not None and (len(args_spec.args) == 1 or args_spec.varargs == 'args'):
            func(unknown_args)
            return

    func()

if __name__ == '__main__':
    main()