# AUTOGENERATED! DO NOT EDIT! File to edit: sample_code_test.ipynb (unless otherwise specified).

__all__ = ['some_function_to_run_on_cloud']

# Cell
import time

def some_function_to_run_on_cloud():
    print('running sample_code_test.some_function_to_run_on_cloud')
    print('in main before sleep 1')
    time.sleep(1)
    print('in main after sleep 2')
    time.sleep(1)
    print('in main after sleep 3')
    time.sleep(1)
    raise Exception('Error in main after sleep 4')
